routes/web.php
<?php

use App\Http\Controllers\Admin\CartController;
use \App\Http\Controllers\Admin\DashboardController;
use \App\Http\Controllers\Admin\CategoriesController;
use \App\Http\Controllers\Admin\ProductsController; 
use \App\Http\Controllers\Admin\CustomersController;
use \App\Http\Controllers\Admin\OrdersController;
use \App\Http\Controllers\Admin\OrderdetailsController;
use App\Http\Controllers\Admin\UsersController;
// use Illuminate\Support\Facades\Auth;
// use \App\Http\Controllers\HomeController;
use Illuminate\Support\Facades\Route;
use \App\Http\Controllers\IndexController;
use \App\Http\Controllers\LoginController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// Admin
Route::group(['middleware'=>'auth','prefix' => 'admin'], function()
{
//     Route::get('/login', function (){
//         return view('layouts.login');
//     });
    Route::resource('/dashboard',DashboardController::class);
    Route::resource('/categories',CategoriesController::class);
    Route::resource('/products',ProductsController::class);
    Route::resource('/customers',CustomersController::class);
    Route::resource('/orders',OrdersController::class);
    Route::resource('/orderdetails',OrderdetailsController::class);
    Route::resource('/users',UsersController::class);
});
// Auth::routes();
// Route::get('/admin/dashboard',[HomeController::class,'index']);

Route::get('admin/login',[LoginController::class,'login'])->name('login');
Route::get('/logout',[LoginController::class,'logout'])->name('logout');
Route::post('/login',[LoginController::class,'postLogin'])->name('postLogin');


//Page

Route::get('/home',[IndexController::class,'index']);
Route::get('/login',[IndexController::class,'login']);
Route::get('/danh-muc-san-pham/{id}',[CategoriesController::class,'show_category']);
Route::get('/chi-tiet-san-pham/{id}',[ProductsController::class,'details_product']);
Route::post('/save_cart',[CartController::class,'save_cart']);


// Route::get('/detail-product',[IndexController::class,'detail_product']);

app/Models/Customer.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Customer extends Model
{
    use HasFactory;
    protected $fillable = [
        "id ","firstName","lastName","phone","address"
    ];

    protected $primaryKey = 'id';
    protected $table = 'customers';
    public $timestamps = true;

    public function get_orders(){
        return $this->hasMany(Order::class);
    }
}

app/Http/Controllers/Admin/CustomersController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\CustomerRequest;
use App\Models\Customer;
use Illuminate\Http\Request;

class CustomersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $items = Customer::all();   
        $params = [
            'items' => $items
        ];
        return view('admin.customers.index',$params);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.customers.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CustomerRequest $request)
    {
        Customer::create($request->all());
        return redirect()->route('customers.index')->with('success','Tạo mới khách hàng thành công');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $item = Customer::find($id);
        $params = [
            'item' => $item
        ];
        return view('admin.customers.edit',$params);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(CustomerRequest $request, $id)
    {
        $item = Customer::find($id);
        $item->firstName = $request->firstName;
        $item->lastName  = $request->lastName;
        $item->phone     = $request->phone;
        $item->address   = $request->address;
        $item->save();

        return redirect()->route('customers.index')->with('success','Cập nhật khách hàng thành công !');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $item = Customer::find($id);
        $item->delete();
        return redirect()->route('customers.index')->with('success','Xóa khách hàng thành công !');
    }
}

resources/views/Admin/customers/create.blade.php
@include('message')
@extends('layouts.admin')

@section('title')
    Thêm mới khách hàng
@endsection

@section('content')
    <div class="row">
        <div class="col-lg-12">
            <div class="box">
                <!-- /.box-header -->
                <div class="box-body">
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif

                    <form action="{{ route('customers.store') }}" method="POST" role="form">
                        @csrf
                        <div class="box-body">

                            <div class="form-group">
                                <label for="name">Tên</label>
                                <input type="text" class="form-control" id="firstName" name="firstName"
                                    value="{{ old('firstName') }}">
                                {{ $errors->default->first('firstName') }}
                            </div>

                            <div class="form-group">
                                <label for="name">Họ</label>
                                <input type="text" class="form-control" id="name" name="lastName"
                                    value="{{ old('lastName') }}">
                                {{ $errors->default->first('lastName') }}
                            </div>

                            <div class="form-group">
                                <label for="name">Điện thoại</label>
                                <input type="text" class="form-control" id="name" name="phone"
                                    value="{{ old('phone') }}">
                                {{ $errors->default->first('phone') }}
                            </div>
                            <div class="form-group">
                                <label for="name">Địa chỉ</label>
                                <input type="text" class="form-control" id="name" name="address"
                                    value="{{ old('address') }}">
                                {{ $errors->default->first('address') }}
                            </div>

                        </div>
                        <!-- /.box-body -->

                        <div class="box-footer">
                            <button type="submit" class="btn btn-primary">Cập nhật</button>
                            <a href="{{ route('customers.index') }}" class="btn btn-primary"> Trở về </a>
                        </div>
                    </form>
                </div>
                <!-- /.box-body -->
            </div>
        </div>
    </div>
@endsection

resources/views/Admin/customers/edit.blade.php
@include('message')
@extends('layouts.admin')

@section('title')
    Chỉnh sửa thông tin khách hàng
@endsection

@section('content')
    <div class="row">
        <div class="col-lg-12">
            <div class="box">
                <!-- /.box-header -->
                <div class="box-body">
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif

                    <form action="{{ route('customers.update', $item->id) }}" method="POST" role="form">
                        @method('PUT')
                        @csrf
                        <div class="box-body">

                            <div class="form-group">
                                <label for="firstName">Tên</label>
                                <input type="text" class="form-control" id="name" name="firstName"
                                    value="{{ $item->firstName }}">
                                {{ $errors->default->first('firstName') }}
                            </div>

                            <div class="form-group">
                                <label for="lastName">Họ</label>
                                <input type="text" class="form-control" id="name" name="lastName"
                                    value="{{ $item->lastName }}">
                                {{ $errors->default->first('lastName') }}
                            </div>

                            <div class="form-group">
                                <label for="phone">Điện thoại</label>
                                <input type="text" class="form-control" id="name" name="phone"
                                    value="{{ $item->phone }}">
                                {{-- {{ $errors->default->first('phone') }} --}}
                            </div>

                            <div class="form-group">
                                <label for="address">Địa chỉ</label>
                                <input type="text" class="form-control" id="name" name="address"
                                    value="{{ $item->address }}">
                                {{ $errors->default->first('address') }}
                            </div>

                        </div>
                        <!-- /.box-body -->

                        <div class="box-footer">
                            <button type="submit" class="btn btn-primary">Cập nhật</button>
                            <a href="{{ route('customers.index') }}" class="btn btn-primary"> Trở về </a>
                        </div>
                    </form>
                </div>
                <!-- /.box-body -->
            </div>
        </div>
    </div>
@endsection

resources/views/Admin/customers/index.blade.php
@extends('layouts/admin')

@section('title')
    Danh sách khách hàng
@endsection

@section('content')
    <div class="row">
        <div class="col-lg-12">
            <div class="box">
                <!-- /.box-header -->
                <div class="box-body">
                    @if (Session::has('success'))
                        <div class="alert alert-success ">
                            {{ Session::get('success') }}
                        </div>
                    @endif
                    <table class="table table-bordered">
                        <tbody>
                            <tr>
                                <th style="width: 10px">#</th>
                                <th>Tên</th>
                                <th>Họ</th>
                                <th>Điện thoại</th>
                                <th>Địa chỉ</th>
                                <th>Ngày tạo</th>
                                <th>Hành Động</th>
                            </tr>
                            @foreach ($items as $item)
                                <tr>
                                    <td>{{ $item->id }}</td>
                                    <td>{{ $item->firstName }}</td>
                                    <td>{{ $item->lastName }}</td>
                                    <td>{{ $item->phone }}</td>
                                    <td>{{ $item->address }}</td>
                                    <td>{{ $item->created_at }}</td>
                                    <td>
                                        <div class="row">
                                            <div class='col-sm-2'>
                                                <a href="{{ route('customers.edit', $item->id) }}"
                                                    class="active styling -edit" ui-tonggle-class="">
                                                    <i class="fa fa-pencil-square-o text-success text-active"></i></a>
                                            </div>
                                            <div class="col-sm-4">
                                                <form id="delete_form"
                                                    action="{{ route('customers.destroy', $item->id) }}" method="post">
                                                    @csrf
                                                    @method ('DELETE')
                                                    <button type="submit" class="active styling-edit" ui-toggle-class=""
                                                        onclick="return confirm('Bạn chắc chắn muốn xóa?')">
                                                        <i class="fa fa-times text-danger text"></i>
                                                    </button>
                                                </form>
                                            </div>


                                            {{-- <a href="{{ route('categories.destroy',$item->id) }}" class="badge bg-red" onclick="return confirm('Bạn chắc chắn muốn xóa?')">Xóa</a> --}}

                                        </div>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
                <!-- /.box-body -->
                <div class="box-footer clearfix">
                    <ul class="pagination pagination-sm no-margin pull-right">
                        <li><a href="#">«</a></li>
                        <li><a href="#">1</a></li>
                        <li><a href="#">2</a></li>
                        <li><a href="#">3</a></li>
                        <li><a href="#">»</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/Admin/customers/show.blade.php
show.blade