routes/web.php
<?php

use App\Http\Controllers\Admin\CartController;
use \App\Http\Controllers\Admin\DashboardController;
use \App\Http\Controllers\Admin\CategoriesController;
use \App\Http\Controllers\Admin\ProductsController; 
use \App\Http\Controllers\Admin\CustomersController;
use \App\Http\Controllers\Admin\OrdersController;
use \App\Http\Controllers\Admin\OrderdetailsController;
use App\Http\Controllers\Admin\UsersController;
// use Illuminate\Support\Facades\Auth;
// use \App\Http\Controllers\HomeController;
use Illuminate\Support\Facades\Route;
use \App\Http\Controllers\IndexController;
use \App\Http\Controllers\LoginController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// Admin
Route::group(['middleware'=>'auth','prefix' => 'admin'], function()
{
//     Route::get('/login', function (){
//         return view('layouts.login');
//     });
    Route::resource('/dashboard',DashboardController::class);
    Route::resource('/categories',CategoriesController::class);
    Route::resource('/products',ProductsController::class);
    Route::resource('/customers',CustomersController::class);
    Route::resource('/orders',OrdersController::class);
    Route::resource('/orderdetails',OrderdetailsController::class);
    Route::resource('/users',UsersController::class);
});
// Auth::routes();
// Route::get('/admin/dashboard',[HomeController::class,'index']);

Route::get('admin/login',[LoginController::class,'login'])->name('login');
Route::get('/logout',[LoginController::class,'logout'])->name('logout');
Route::post('/login',[LoginController::class,'postLogin'])->name('postLogin');


//Page

Route::get('/home',[IndexController::class,'index']);
Route::get('/login',[IndexController::class,'login']);
Route::get('/danh-muc-san-pham/{id}',[CategoriesController::class,'show_category']);
Route::get('/chi-tiet-san-pham/{id}',[ProductsController::class,'details_product']);
Route::post('/save_cart',[CartController::class,'save_cart']);


// Route::get('/detail-product',[IndexController::class,'detail_product']);

app/Models/Orderdetail.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Models\Order;
use App\Models\Product;
use Illuminate\Database\Eloquent\SoftDeletes;

class Orderdetail extends Model
{
    use HasFactory;
    use SoftDeletes;
    public $timestamps = false;
    public function order(){
        return $this->belongsTo(Order::class, 'order_id', 'id');
    }
    public function product(){
        return $this->belongsTo(Product::class, 'product_id', 'id');
    }

}

app/Http/Controllers/Admin/OrderdetailsController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\OrderdetailRequest;
use App\Models\Orderdetail;
use App\Models\Order;
use App\Models\Product;

class OrderdetailsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $items  = Orderdetail::with('product')->get();
        $items  = Orderdetail::with('order')->get();
        $params = [
            'items' => $items
        ];  
        return view('admin.orderdetails.index', $params);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $orders = Order::all();
        $products = Product::all();
        $params = [
            'orders'=> $orders,
            'products' =>$products
        ];
        return view('admin.Orderdetails.create', $params);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(OrderdetailRequest $request)
    {
        $orderdetail = new Orderdetail();
        $orderdetail->order_id = $request->order_id;
        $orderdetail->product_id = $request->product_id;
        $orderdetail->quantityOrdered = $request->quantityOrdered;
        $orderdetail->priceEach = $request->priceEach;
        $orderdetail->totalOrder = $request->totalOrder;
        $orderdetail->save();

        return redirect()->route('orderdetails.index')->with('success','');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $orders = Order::all();
        $products = Product::all();
        $item = Orderdetail::find($id);
        $params = [
            'orders' => $orders,
            'products' => $products,
            'item' => $item
        ];
        return view('admin.orderdetails.edit', $params);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(OrderdetailRequest $request, $id)
    {
        $orderdetail = Orderdetail::find($id);
        $orderdetail->order_id = $request->order_id;
        $orderdetail->product_id = $request->product_id;
        $orderdetail->quantityOrdered = $request->quantityOrdered;
        $orderdetail->priceEach = $request->priceEach;
        $orderdetail->totalOrder = $request->totalOrder;
        $orderdetail->save();
        
        return redirect()->route('orderdetails.index')->with('success','Chỉnh sửa thành công !');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
       $item = Orderdetail::find($id);
       $item->delete();
       return redirect()->route('orderdetails.index')->with('success','Xóa thành công'); 
    }
}

resources/views/Admin/orderdetails/create.blade.php
{{-- @include('message') --}}
@extends('layouts.admin')

@section('title')
    Tạo mới
@endsection

@section('content')
    <div class="row">
        <div class="col-lg-12">
            <div class="box">
                <!-- /.box-header -->
                <div class="box-body">
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif

                    <form action="{{ route('categories.store') }}" method="POST" role="form">
                        @csrf
                        <div class="box-body">

                            <div class="form-group">
                                <label for="name">Order_id</label>
                                <select name="order_id" class="form-control">
                                    @foreach ($orders as $order)
                                        <option value="{{ $order['id'] }}">{{ $order['id'] }}</option>
                                    @endforeach
                                </select>
                                {{ $errors->default->first('order_id') }}
                            </div>

                            <div class="form-group">
                                <label for="description">Tên sản phẩm</label>
                                <textarea name="category_desc" id="description" class="form-control"
                                    value="{{ old('category_desc') }}"></textarea>
                                {{ $errors->default->first('category_desc') }}
                            </div>

                            <div class="form-group">
                                <label for="status">Trạng thái</label>
                                <select name="category_status" class="form-select" id="inputGroupSelect02">
                                    <option value="0">Kích hoạt</option>
                                    <option value="1">Không kích hoạt</option>
                                </select>
                            </div>

                        </div>
                        <!-- /.box-body -->

                        <div class="box-footer">
                            <button type="submit" class="btn btn-primary">Cập nhật</button>
                            <a href="{{ route('categories.index') }}" class="btn btn-primary"> Trở về </a>
                        </div>
                    </form>
                </div>
                <!-- /.box-body -->
            </div>
        </div>
    </div>
@endsection

resources/views/Admin/orderdetails/edit.blade.php
@include('message')
@extends('layouts.admin')

@section('title')
    Chỉnh sửa chi tiết đơn hàng
@endsection

@section('content')
    <div class="row">
        <div class="col-lg-12">
            <div class="box">
                <!-- /.box-header -->
                <div class="box-body">
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif

                    <form action="{{ route('orderdetails.update', $item->id) }}" method="POST" role="form">
                        @method('PUT')
                        @csrf
                        <div class="box-body">          
                            <div class="form-group">
                                <label for="name">Order_id</label>
                                <select name="order_id" class="form-control">
                                    @foreach ($orders as $order)
                                        <option value="{{ $order['id'] }}">{{ $order['id'] }}</option>
                                    @endforeach
                                </select>
                                {{ $errors->default->first('order_id') }}
                            </div>
                            <div class="form-group">
                                <label for="name">Tên sản phẩm</label>
                                <select name="product_id" class="form-control">
                                    @foreach ($products as $product)
                                        <option value="{{ $product['id'] }}">{{ $product['name'] }}</option>
                                    @endforeach
                                </select>
                                {{ $errors->default->first('product_id') }}
                            </div>
                                        
                            <div class="form-group">
                                <label for="name">Giá mỗi sản phẩm</label>
                                <input type="text" class="form-control" id="name" name="priceEach" value="{{ $item->priceEach }}">
                                {{ $errors->default->first('priceEach') }}
                            </div>
                            <div class="form-group">
                                <label for="name">Số lượng đã đặt</label>
                                <input type="text" class="form-control" id="name" name="quantityOrdered" value="{{ $item->quantityOrdered }}">
                                {{ $errors->default->first('quantityOrdered') }}
                            </div>
                            <div class="form-group">
                                <label for="name">Tổng tiền</label>
                                <input type="text" class="form-control" id="name" name="totalOrder" value="{{ $item->totalOrder }}">
                                {{ $errors->default->first('totalOrder') }}
                            </div>
                                

                        </div>
                        <!-- /.box-body -->

                        <div class="box-footer">
                            <button type="submit" class="btn btn-primary">Cập nhật</button>
                            <a href="{{ route('orderdetails.index') }}" class="btn btn-primary"> Trở về </a>

                        </div>
                    </form>
                </div>
                <!-- /.box-body -->
            </div>
        </div>
    </div>
@endsection

resources/views/Admin/orderdetails/index.blade.php
@extends('layouts/admin')

@section('title')
    Chi tiết đơn hàng
@endsection

@section('content')
    <div class="row">
        <div class="col-lg-12">
            <div class="box">
                <!-- /.box-header -->
                <div class="box-body">
                    @if (Session::has('success'))
                        <div class="alert alert-success ">
                            {{ Session::get('success') }}
                        </div>
                    @endif
                    <table class="table table-bordered">
                        <tbody>
                            <tr>
                                <th>Order_id</th>
                                <th>Tên sản phẩm</th>
                                <th>Giá mỗi sản phẩm</th>
                                <th>Số lượng đã đặt</th>
                                <th>Tổng tiền</th>
                                <th>Hành Động</th>
                            </tr>
                            @foreach ($items as $item)
                                <tr>
                                    <td>{{ $item->order['id'] }}</td>
                                    <td>{{ $item->product['name'] }}</td>
                                    <td>{{ $item->priceEach }}</td>
                                    <td>{{ $item->quantityOrdered }}</td>
                                    <td>{{ $item->totalOrder }}</td>
                                    <td>
                                        <div class="row">
                                            <div class='col-sm-2'>
                                                <a href="{{ route('orderdetails.edit', $item->id) }}"
                                                    class="active styling -edit" ui-tonggle-class="">
                                                    <i class="fa fa-pencil-square-o text-success text-active"></i></a>
                                            </div>
                                            <div class="col-sm-4">
                                                <form id="delete_form" action="{{ route('orderdetails.destroy', $item->id) }}"
                                                    method="post">
                                                    @csrf
                                                    @method ('DELETE')
                                                    <button type="submit" class="active styling-edit" ui-toggle-class=""
                                                        onclick="return confirm('Bạn chắc chắn muốn xóa?')">
                                                        <i class="fa fa-times text-danger text"></i>
                                                    </button>
                                                </form>
                                            </div>
                                            {{-- <a href="{{ route('categories.destroy',$item->id) }}" class="badge bg-red" onclick="return confirm('Bạn chắc chắn muốn xóa?')">Xóa</a> --}}

                                        </div>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
                <!-- /.box-body -->
                <div class="box-footer clearfix">
                    <ul class="pagination pagination-sm no-margin pull-right">
                        <li><a href="#">«</a></li>
                        <li><a href="#">1</a></li>
                        <li><a href="#">2</a></li>
                        <li><a href="#">3</a></li>
                        <li><a href="#">»</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/Admin/orderdetails/show.blade.php
show.blade